
---
- name: Install Java and Jenkins on localhost (master)
  hosts: Master
  become: true

  tasks:
    - name: Execute Java install script
      script: ./scripts/java_script.sh

    - name: Execute Jenkins install script
      script: ./scripts/jenkins_script.sh
    
    - name: Execute the mysql script
      script: ./scripts/mysql_script.sh

    - name: Execute the AWS CLI script
      script: ./scripts/awscli_script.sh

    - name: Execute the docker script
      script: ./scripts/docker_script.sh

    - name: Execute the kubectl script
      script: ./scripts/kubectl_script.sh

    - name: Execute the helm script
      script: ./scripts/helm_script.sh
    



- name: Install docker,sonarqube on sonarqube server
  hosts: sonarqube
  become: true

  tasks:
    - name: Create directory to store scripts on remote server
      file:
        path: /home/ubuntu/scripts
        state: directory
        mode: '0755'

    - name: Copy Docker script to agent server
      copy:
        src: ./scripts/docker_script.sh
        dest: /home/ubuntu/scripts/docker_script.sh
        mode: '0755'

    - name: Execute the docker script
      shell: /home/ubuntu/scripts/docker_script.sh

    - name: Pull SonarQube image
      shell: docker pull sonarqube:10.6-community

    - name: run sonarqube container
      shell: docker run -d --name sonarqube-custom -p 9000:9000 sonarqube:10.6-community



- name: Install prometheus and grafana server
  hosts: monitoring
  become: true

  tasks:
    - name: Create directory to store scripts on remote server
      file:
        path: /home/ubuntu/scripts
        state: directory
        mode: '0755'

    # - name: Copy Java script to agent server
    #   copy:
    #     src: ./scripts/java_script.sh
    #     dest: /home/ubuntu/scripts/java_script.sh
    #     mode: '0755'

    # - name: Execute the Java script
    #   shell: /home/ubuntu/scripts/java_script.sh


  


