---
- name: Install Java and Jenkins using shell script
  hosts: localhost
  become: true

  tasks:
    - name: Ensure Java install script is executable
      file:
        path: /root/ansible/installation_scripts/java_script.sh
        mode: '0755'
        state: file

    - name: Execute Java install script
      script: /root/ansible/installation_scripts/java_script.sh

    - name: Ensure Jenkins install script is executable
      file:
        path: /root/ansible/installation_scripts/jenkins_script.sh
        mode: '0755'
        state: file

    - name: Execute Jenkins install script
      script: /root/ansible/installation_scripts/jenkins_script.sh


- name: Install Terraform using shell script
  hosts: agent
  become: true

  tasks:
    - name: Ensure Terraform install script is executable
      file:
        path: /root/ansible/installation_scripts/terraform_script.sh
        mode: '0755'
        state: file

    - name: Execute Terraform install script
      script: /root/ansible/installation_scripts/terraform_script.sh  # use script if file is in localhost or use shell if file is on remote host












---
- name: Install Java and Jenkins on localhost (master)
  hosts: localhost
  become: true

  tasks:
    - name: Execute Java install script
      script: ./scripts/java_script.sh

    - name: Execute Jenkins install script
      script: ./scripts/jenkins_script.sh



- name: Install java, AWS CLI, Docker, kubectl, Helm on agent server
  hosts: agent
  become: true

  tasks:
    - name: Create directory to store scripts on remote server
      file:
        path: /home/ubuntu/scripts
        state: directory
        mode: '0755'

    - name: Copy AWS CLI script to agent server
      copy:
        src: ./scripts/awscli_script.sh
        dest: /home/ubuntu/scripts/awscli_script.sh
        mode: '0755'

    - name: Execute the AWS CLI script
      shell: /home/ubuntu/scripts/awscli_script.sh


    - name: Copy Docker script to agent server
      copy:
        src: ./scripts/docker_script.sh
        dest: /home/ubuntu/scripts/docker_script.sh
        mode: '0755'

    - name: Execute the docker script
      shell: /home/ubuntu/scripts/docker_script.sh


    - name: Copy kubectl script to agent server
      copy:
        src: ./scripts/kubectl_script.sh
        dest: /home/ubuntu/scripts/kubectl_script.sh
        mode: '0755'

    - name: Execute the kubectl script
      shell: /home/ubuntu/scripts/kubectl_script.sh


    - name: Copy helm script to agent server
      copy:
        src: ./scripts/helm_script.sh
        dest: /home/ubuntu/scripts/helm_script.sh
        mode: '0755'

    - name: Execute the kubectl script
      shell: /home/ubuntu/scripts/helm_script.sh


- name: Create a database on AWS RDS
  hosts: localhost
  gather_facts: false
  vars:
    db_host: "mydb.cujwsmiewj2i.us-east-1.rds.amazonaws.com"
    db_user: "admin"
    db_password: "Rajesh1234"
    db_name: "student_db"

  tasks:
    - name: Create database on RDS
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_port: 3306




- name: Install java,docker agent server
  hosts: sonarqube
  become: true

  tasks:
    - name: Create directory to store scripts on remote server
      file:
        path: /home/ubuntu/scripts
        state: directory
        mode: '0755'

    - name: Copy Docker script to agent server
      copy:
        src: ./scripts/docker_script.sh
        dest: /home/ubuntu/scripts/docker_script.sh
        mode: '0755'

    - name: Execute the docker script
      shell: /home/ubuntu/scripts/docker_script.sh

    - name: run sonarqube container
      shell: docker run --name sonarqube-custom -p 9000:9000 sonarqube:10.6-community